var i = 6;
document.write(i + '<br/>');
i = i + 6;
document.write(i + '<br/>');
i = i + 6;
document.write(i + '<br/>');
i = i + 6;
document.write(i + '<br/>');
i = i + 6;
document.write(i + '<br/>');
i = i + 6;
document.write(i + '<br/>');